<a href="https://colab.research.google.com/github/24f3005028/MLP-ASSIGNMENTS/blob/main/MLP_OPPE2_MODEL_BUILDING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Import**

In [2]:
import pandas as pd
import numpy as np

just download the dataset and go to files in colab and then on top left click import to import the downloaded dataset simple

Data PreProcessing Dataset

In [4]:
dataset_url = "/content/Preprocessing_V1.csv"
df = pd.read_csv(dataset_url)

In [5]:
df.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
0,Female,75.0,Yes,No,Yes,Self-employed,City,54.6,35.1,never smoked,No
1,Female,49.0,No,No,Yes,Private,Village,108.8,26.7,smokes,No
2,Male,32.0,No,No,Yes,Private,City,64.1,23.4,smokes,No
3,Male,78.0,No,No,Yes,Self-employed,City,219.2,27.4,Unknown,Yes
4,Male,39.0,No,No,Yes,Private,City,55.4,41.6,formerly smoked,No

Model Building Dataset

In [6]:
mb_dataset_url = "/content/Copy of preprocessed_data.csv"
mb_df = pd.read_csv(mb_dataset_url)

In [7]:
mb_df.head()

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,...,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,satisfaction
0,0.833333,0.062919,1.0,1.0,0.6,1.00,0.8,0.8,0.75,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,0.628205,0.015831,1.0,1.0,1.0,1.00,1.0,0.8,0.75,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.192308,0.164603,0.6,0.4,0.8,0.25,0.6,0.6,0.50,0.6,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0.628205,0.142886,0.4,0.6,0.4,0.50,0.4,0.4,0.25,0.4,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,0.525641,0.070631,0.6,0.4,0.4,0.25,0.6,0.6,0.50,0.6,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

Warning: Total number of columns (28) exceeds max_columns (20) limiting to first (20) columns.

# **Model Building**

# EXAM TIPS
1. import the dataset and learn about the train_test_split.

2. then via the sklearn documentation first search and import the model which is required in the question and then via the ?ModelName learn how to set the parameters and then solve the solution

##Q2 [Marks =3] Break the dataset into features(`X`) and label (`y`), where the column `satisfaction` goes to `y` and the rest of the columns go to `X`. How many data points belonging to `satisfaction` value 1 are there in the dataset ? [NAT]

Sol: In supervised learning, you separate inputs (features) and output (label). Here, satisfaction is the binary label (0/1), and all other columns are features.

To answer the question, you simply count how many rows in y are equal to 1 using value_counts or a boolean mask

In [11]:
X = mb_df.drop(columns=['satisfaction'])
Y = mb_df['satisfaction']

Y.value_counts()

Number of satisfaction==1: 8916

##Q3 [Marks : 3] Split the dataset into train and test dataset into the `80:20` ratio while keeping `random_state =64`. What is the shape of the training label vector(`y_train`) dataset?

(A) (20000,)

(B) (16574,27)

(C) (20024,14)

(D) (4522,98)

(E) (16574,)

##Sol:
 train_test_split is used to evaluate models: training data is used to fit, and test data is used to measure performance on unseen examples.

OPPE always fixes test_size=0.2 and a specific random_state so your answer is reproducible; you then inspect y_train.shape.

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, random_state=64, test_size=0.2
)

In [14]:
print("Y_train shape:", Y_train.shape)

Y_train shape: (16574,)

##Q4 [4 marks][NAT] Take `LogisticRegression` estimator with following parameters for training:
  - Use `sag` as solver
  - Set random state to be equal to 64
  - Tolerance for stopping criteria to be 1e-3
  - Maximum number of iterations taken for the solvers to converge to be 100

Enter the recall score for the given model using test set(X_test, y_test)

##Sol:
Logistic regression is a standard linear classifier for binary labels like satisfaction.

Recall measures how many of the positive samples (here label 1) you correctly identify; OPPE uses it to check if you can compute different metrics, not just accuracy.

You fit on training data, predict on test data, and compute recall_score(y_test, y_pred). By default, pos_label=1.

In [15]:
from sklearn.linear_model import LogisticRegression

In [21]:
model = LogisticRegression(
    solver='sag',
    random_state=64,
    tol=1e-3,
    max_iter=100
)

In [22]:
model.fit(X_train, Y_train)
pred = model.predict(X_test)

In [23]:
from sklearn.metrics import recall_score
recall_sr = recall_score(Y_test, pred)
print("Logistic recall:", recall_sr)

Logistic recall: 0.8435599778883361


# (Instruction for Question 5 and 6)

Instantiate a perceptron classifier with following parameters:-

-  Fit the intercept
-  Put warm start to be False
-  random_state=64

## Q5[Marks : 4][NAT] Fit this perceptron model with the training dataset and write the accuracy for the test data.

V1: 0.842 (range: 0.82,0.86)

In [27]:
from sklearn.linear_model import Perceptron
model2 = Perceptron(
    warm_start = False,
    random_state = 64,
)

In [28]:
model2.fit(X_train, Y_train)
m2_pred = model2.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(Y_test, m2_pred)
print(acc_score)

0.8424227799227799

## Q6[Marks : 4]  [NAT] What is the value of bias (intercept) for the perceptron model you got (upto 1 decimal point) ?


Ans:

V1: -10.0

## Sol:

Linear models separate weights and bias: prediction is
*𝑤
𝑇
𝑥
+
𝑏*
, where intercept_ is the bias term.

Perceptron stores coef_ (weights) and intercept_ (bias), so you just read per.intercept_ after fitting.

In [33]:
bias = model2.intercept_
print("Perceptron intercept_:", bias)

Perceptron intercept_: [-10.]

##Q 7  [6 marks] [NAT] Use  `SGDClassifier` on the training dataset (`X_train` and `y_train`) to train the model. Use the following parameters:

1. `log_loss`is the loss function to be used
2. apply ridge regularization,
3. maximum number of passes over the training data is 10
4. constant learning rate of 0.01,
5. regularization rate value is 0.001,
6. Take random_state=64.
7. Set warm_start as True

Note : Please ignore the convergence warning.

Using above model, calculate and write the correct value of f1_score for the test set.

Ans:

V1. 0.861 (Range: 0.850, 0.870)

In [35]:
from sklearn.linear_model import SGDClassifier

model3 = SGDClassifier(
    loss="log_loss",
    max_iter=10,
    penalty="l2", #specifies ridge
    random_state=64,
    learning_rate="constant",
    eta0=0.01,
    warm_start=True,
    alpha=0.001 # specifies regularisation rate value
)

In [39]:
model3.fit(X_train, Y_train)
m3_pred = model3.predict(X_test)

In [42]:
from sklearn.metrics import f1_score

m3_f1_score = f1_score(Y_test, m3_pred)
print(m3_f1_score)

0.8644310690742333


## Q8. [4 marks] [MCQ] Use Gridsearchcv with KNeighborsClassifier estimator, accuracy as scoring parameter, cv= 5. Consider [1,3,7,11] as K values to be examined.
* Consider following parameters for KNeighborsClassifier:

 - Take metric as 'minkowski',
 - Set P value as 2

- Keep other parameter values as default values.

What is the best value of K you obtained using the above instructions?

Options

A) 1

B) 3

C) 7

D) 11

Ans:

V1: C

## Sol:
Use KNeighborsClassifier + GridSearchCV:

metric='minkowski', p=2 (Euclidean distance),

n_neighbors in [1, 3, 7, 11],

scoring='accuracy', cv=5.
Report best k.

Idea and approach
KNN classifies a point by the majority label among its nearest neighbours; n_neighbors controls bias–variance trade‑off.

GridSearchCV tests each n_neighbors across 5 folds of training data, scoring by accuracy; the best hyperparameters minimize cross‑validated error

In [46]:
from sklearn.neighbors import KNeighborsClassifier
model4 = KNeighborsClassifier(
    metric="minkowski",
    p=2
)

In [49]:
from sklearn.model_selection import GridSearchCV

param_grid={
    "n_neighbors":[1,3,7,11]
}
tuned_m4 = GridSearchCV(estimator=model4, param_grid=param_grid, scoring="accuracy",cv=5)

In [51]:
tuned_m4.fit(X_train, Y_train)
#m4_pred = tuned_m4.predict(X_test)
tuned_m4.best_params_

{'n_neighbors': 7}

# **(Common Instructions for Q9 to Q12)**

Take DecisionTreeClassifier(random_state = 64) estimator with GridSearchCV. Hyperparameter tuning to be done over the following parameters:

- Criterion as 'entropy' or 'gini'

- Splitter as 'random' or 'best'

- Minimum number of samples per leaf as [2,4,6,8,10]

- Maximum depth as [3,4,5,6]

- Use cross validation = 4


Use the best model from above hyper parameter turing process to answer following questions:

## Q9. [Marks: 4][NAT] Enter the value of the precision on the test set using the best model:

 Answer:

V1: 0.905 (Range : 0.89 ,0.93)

In [54]:
# Model Building
from sklearn.tree import DecisionTreeClassifier
model5 = DecisionTreeClassifier(
    random_state=64,
)

In [55]:
# Model Finetuning
from sklearn.model_selection import GridSearchCV
param_grid = {
    "criterion":["entropy","gini"],
    "splitter":["random", "best"],
    "min_samples_leaf":[2,4,6,8,10],
    "max_depth":[3,4,5,6],
}

finetuned_m5 = GridSearchCV(estimator=model5, param_grid=param_grid, cv=4)

In [56]:
finetuned_m5.fit(X_train, Y_train)

GridSearchCV(cv=4, estimator=DecisionTreeClassifier(random_state=64),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [3, 4, 5, 6],
                         'min_samples_leaf': [2, 4, 6, 8, 10],
                         'splitter': ['random', 'best']})

In [58]:
from sklearn.metrics import precision_score
m5_pred = finetuned_m5.predict(X_test)
m5_ps = precision_score(Y_test, m5_pred)

In [59]:
print(m5_ps)

0.9052517596101787

## Q10:[Marks: 4] [MCQ] Enter the value of max_depth of the best estimator you got after training with GridSearchCV.

A) 3

B) 4

C) 5

D) 6

Answer: D (all versions)

In [60]:
finetuned_m5.best_estimator_

DecisionTreeClassifier(max_depth=6, min_samples_leaf=2, random_state=64)

## Q11[Marks: 4 ][NAT] Enter the value of min_samples_leaf of the best estimator after training with GridSearchCV.

A) 2

B) 4

C) 6

D) 8

E) 10


Answer:

V1: A

In [61]:
finetuned_m5.best_estimator_

DecisionTreeClassifier(max_depth=6, min_samples_leaf=2, random_state=64)

## Q12[Marks : 4] [NAT]  What is the number of nodes in the optimal tree?

Answer:

V1: 79

In [65]:
?finetuned_m5.best_estimator_.tree_

In [66]:
finetuned_m5.best_estimator_.tree_.node_count

79

## Q13. [Marks: 4 ][MCQ] Take RandomForestClassifier (random state to be 64) with GridSearchCV to tune the number of decision trees with the training set. The number of trees in forest can range from 5 to 10 (both inclusive). Mark the number of decision trees in the best estimator provided by the grid search.

A. 5

B. 6

C. 7

D. 8

E. 9

F. 10

Answer:

V1: E

In [75]:
from sklearn.ensemble import RandomForestClassifier

model6 = RandomForestClassifier(
    random_state = 64
)

from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators":[5,6,7,8,9,10],
}

finetuned_m6 = GridSearchCV(estimator=model6, param_grid=param_grid)
finetuned_m6.fit(X_train, Y_train)

GridSearchCV(estimator=RandomForestClassifier(random_state=64),
             param_grid={'n_estimators': [5, 6, 7, 8, 9, 10]})

In [81]:

finetuned_m6.best_params_

{'n_estimators': 9}

# **(Common Instructions for Q14,Q15)**
##Take an adaboost model with following hyperparameter values and tune it using GridsearchCV.

- Use n_estimators as [10,20,30]
- random_state = 64
- Use learning_rate as [0.5,1,2]
- Take cv value= 5

## Q14[Marks: 3] [NAT] Train the 'model' using above instructions and use the best estimator to calculate the total number of misclassified samples for the test data and submit the value.

Answer:

V1: 422   (Range: 418,425)

In [83]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV

model7 = AdaBoostClassifier(random_state=64)
param_grid = {
    "n_estimators":[10,20,30],
    "learning_rate":[0.5,1,2]
}
finetuned_m7 = GridSearchCV(estimator=model7, param_grid=param_grid, cv=5)
finetuned_m7.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=AdaBoostClassifier(random_state=64),
             param_grid={'learning_rate': [0.5, 1, 2],
                         'n_estimators': [10, 20, 30]})

In [87]:
from sklearn.metrics import confusion_matrix
m7_pred = finetuned_m7.predict(X_test)
confusion_matrix(Y_test, m7_pred)

array([[2156,  179],
       [ 243, 1566]])

## Q15[Marks: 3] Mark  the value of `n_estimators` of the best model after training with GridSearchCV. [MCQ]

Options:

A) 10

B) 20

C) 30

D) None of these

Answer: C (all versions)

In [88]:
finetuned_m7.best_estimator_

AdaBoostClassifier(learning_rate=1, n_estimators=30, random_state=64)

## Q16 [6 marks] Apply `GridSearchCV` using the support vector machine (SVM) classifier on the training dataset `X_train, y_train` and calculate the best value of `C` and `kernel` from the values below.

####use below hyperparameter values to tune the mode
* `kernel':['linear', 'rbf'],
* 'C':[1, 10]`)

Which of the following options represent the best parameters?

options:

A. {'C': 1, 'kernel': 'rbf'}

B. {'C': 10, 'kernel': 'rbf'}

C. {'C':  1, 'kernel': 'linear'}

D. {'C': 10, 'kernel': 'linear'}


Answer: B

In [90]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

model8 = SVC()

param_grid = {
    'kernel':['linear', 'rbf'],
    'C':[1, 10],
}

finetuned_m8 = GridSearchCV(estimator=model8 , param_grid=param_grid)
finetuned_m8.fit(X_train, Y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ['linear', 'rbf']})

In [93]:
finetuned_m8.best_params_

{'C': 10, 'kernel': 'rbf'}