<a href="https://colab.research.google.com/github/24f3005028/MLP-ASSIGNMENTS/blob/main/MLP_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Student Project: Real Estate Data Analysis
This notebook contains the solutions for the graded dataset assignment.

### 1. Setup and Data Loading

In [ ]:
import pandas as pd
import gdown

# Download and load dataset
file_id = '1x-phOl0d1QHy4ea8O_hHdz_wBGH35dRz'
url = f'https://drive.google.com/uc?id={file_id}&export=download'
gdown.download(url, 'dataset.csv', quiet=True)

df = pd.read_csv('dataset.csv')
df.replace('?', pd.NA, inplace=True)
print(f"Dataset loaded with {df.shape[0]} rows and {df.shape[1]} columns.")

Dataset loaded with 10000 rows and 12 columns.

### 2. Data Inspection

In [ ]:
display(df.head())
print("Columns:", df.columns.tolist())

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,<NA>,Detached House,3,2,1092.0,1.025953,East

Columns: ['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property', 'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area', 'property_tax_rate', 'Face']

### 3. Basic Row and Column Selection

In [ ]:
# Q1 & Q2: Even indexed rows
q1_df = df.iloc[::2]
ans1 = q1_df.iloc[0, 3]
ans2 = q1_df.iloc[332, 3]

# Q3: Odd indexed rows
q3_df = df.iloc[1::2]
ans3 = q3_df.iloc[332, 3]

# Q4: Odd indexed columns
q4_df = df.iloc[:, 1::2]
ans4 = q4_df.iloc[100, 5]

# Q5: Even rows and columns
q5_df = df.iloc[::2, ::2]
ans5 = q5_df.iloc[255, 3]

print(f"Q1: {ans1}, Q2: {ans2}, Q3: {ans3}, Q4: {ans4}, Q5: {ans5}")

Q1: 111440.0, Q2: 256200.0, Q3: 352940.0, Q4: West, Q5: Detached House

### 4. Advanced Filtering and Aggregation

In [ ]:
# Q6: Recent 6 years
recent_yrs = sorted(df['Year'].unique())[-6:]
ans6 = df[df['Year'].isin(recent_yrs)].shape[0]

# Q7 & Q8: Rooms and Bathrooms
ans7 = df[(df['num_rooms'] == 3) & (df['num_bathrooms'] == 3)].shape[0]
ans8 = df[(df['num_rooms'] == 3) | (df['num_bathrooms'] == 3)].shape[0]

# Q9: Specific 2022 Greenwich criteria
ans9 = df[(df['Year'] == 2022) & (df['Locality'] == 'Greenwich') & (df['num_rooms'] == 3) & (df['Face'].isin(['North', 'East']))].shape[0]

# Q10: August sales
ans10 = df[pd.to_datetime(df['Date']).dt.month == 8].shape[0]

# Q11: Highest average price locality
ans11 = df.groupby('Locality')['Sale Price'].mean().idxmax()

print(f"Q6: {ans6}, Q7: {ans7}, Q8: {ans8}, Q9: {ans9}, Q10: {ans10}, Q11: {ans11}")

Q6: 4749, Q7: 2730, Q8: 8591, Q9: 42, Q10: 1050, Q11: Greenwich

### 5. Summary Table

In [ ]:
results = {
    "Question": ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8", "Q9", "Q10", "Q11"],
    "Result": [ans1, ans2, ans3, ans4, ans5, ans6, ans7, ans8, ans9, ans10, ans11]
}
display(pd.DataFrame(results))

   Question          Result
0        Q1        111440.0
1        Q2        256200.0
2        Q3        352940.0
3        Q4            West
4        Q5  Detached House
5        Q6            4749
6        Q7            2730
7        Q8            8591
8        Q9              42
9       Q10            1050
10      Q11       Greenwich

# Real Estate Dataset Analysis
## Google Colab Notebook

This notebook presents a structured solution to the dataset questions using Python and pandas.

---

## Step 1: Import Libraries

In [ ]:
import pandas as pd
import gdown

## Step 2: Load Dataset

In [ ]:
file_id = '1x-phOl0d1QHy4ea8O_hHdz_wBGH35dRz'
url = f'https://drive.google.com/uc?id={file_id}&export=download'
gdown.download(url, 'dataset.csv', quiet=True)

df = pd.read_csv('dataset.csv')
print("Dataset loaded successfully.")
print("Dataset Shape:", df.shape)

Dataset loaded successfully.
Dataset Shape: (10000, 12)

## Step 3: Inspect Data

In [ ]:
display(df.head())
print("\nColumn Names:")
print(df.columns.tolist())

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

Column Names:
['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property', 'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area', 'property_tax_rate', 'Face']

## Question 1

**Task:** Select all even indexed rows and find the value in the 3rd indexed column of the 0th indexed row.

In [ ]:
q1_df = df.iloc[::2]
q1_answer = q1_df.iloc[0, 3]
print("Question 1 Answer:", q1_answer)

Question 1 Answer: 111440.0

## Question 2

**Task:** Select all even indexed rows and find the value in the 3rd indexed column of the 332nd indexed row.

In [ ]:
q2_answer = q1_df.iloc[332, 3]
print("Question 2 Answer:", q2_answer)

Question 2 Answer: 256200.0

## Question 3

**Task:** Select all odd indexed rows and find the value in the 3rd indexed column of the 332nd indexed row.

In [ ]:
q3_df = df.iloc[1::2]
q3_answer = q3_df.iloc[332, 3]
print("Question 3 Answer:", q3_answer)

Question 3 Answer: 352940.0

## Question 4

**Task:** Select all odd indexed columns and find the value in the 5th indexed column of the 100th indexed row.

In [ ]:
q4_df = df.iloc[:, 1::2]
q4_answer = q4_df.iloc[100, 5]
print("Question 4 Answer:", q4_answer)

Question 4 Answer: West

## Question 5

**Task:** Select all even indexed rows and even indexed columns, then find the value in the 3rd indexed column of the 255th indexed row.

In [ ]:
q5_df = df.iloc[::2, ::2]
q5_answer = q5_df.iloc[255, 3]
print("Question 5 Answer:", q5_answer)

Question 5 Answer: Detached House

## Question 6

**Task:** Determine the number of samples belonging to the six most recent years.

In [ ]:
recent_years = sorted(df['Year'].unique())[-6:]
q6_answer = df[df['Year'].isin(recent_years)].shape[0]
print("Question 6 Answer:", q6_answer)

Question 6 Answer: 4749

## Question 7

**Task:** Determine the number of samples where `num_rooms = 3` and `num_bathrooms = 3`.

In [ ]:
q7_answer = df[(df['num_rooms'] == 3) & (df['num_bathrooms'] == 3)].shape[0]
print("Question 7 Answer:", q7_answer)

Question 7 Answer: 2730

## Question 8

**Task:** Determine the number of samples where `num_rooms = 3` or `num_bathrooms = 3`.

In [ ]:
q8_answer = df[(df['num_rooms'] == 3) | (df['num_bathrooms'] == 3)].shape[0]
print("Question 8 Answer:", q8_answer)

Question 8 Answer: 8591

## Question 9

**Task:** In 2022, count the number of houses in Greenwich with `num_rooms = 3` and facing either North or East.

In [ ]:
q9_answer = df[
    (df['Year'] == 2022) &
    (df['Locality'] == 'Greenwich') &
    (df['num_rooms'] == 3) &
    (df['Face'].isin(['North', 'East']))
].shape[0]
print("Question 9 Answer:", q9_answer)

Question 9 Answer: 42

## Question 10

**Task:** Count the number of samples corresponding to the month of August across all years.

In [ ]:
q10_answer = df[pd.to_datetime(df['Date']).dt.month == 8].shape[0]
print("Question 10 Answer:", q10_answer)

Question 10 Answer: 1050

## Question 11

**Task:** Identify the locality with the highest average Sale Price.

In [ ]:
q11_answer = df.groupby('Locality')['Sale Price'].mean().idxmax()
print("Question 11 Answer:", q11_answer)

Question 11 Answer: Greenwich

## Final Answers Summary

In [ ]:
answers = {
    "Q1": q1_answer, "Q2": q2_answer, "Q3": q3_answer, "Q4": q4_answer, "Q5": q5_answer,
    "Q6": q6_answer, "Q7": q7_answer, "Q8": q8_answer, "Q9": q9_answer, "Q10": q10_answer,
    "Q11": q11_answer
}
summary_df = pd.DataFrame(list(answers.items()), columns=["Question", "Answer"])
display(summary_df)

   Question          Answer
0        Q1        111440.0
1        Q2        256200.0
2        Q3        352940.0
3        Q4            West
4        Q5  Detached House
5        Q6            4749
6        Q7            2730
7        Q8            8591
8        Q9              42
9       Q10            1050
10      Q11       Greenwich

GRADED ASSIGNMENT WEEK 1

ASSIGNMENT 1.1

In [ ]:
import pandas as pd
from google.colab import files

import gdown

file_id = '1x-phOl0d1QHy4ea8O_hHdz_wBGH35dRz'
url = f'https://drive.google.com/uc?id={file_id}&export=download'

gdown.download(url, 'dataset.csv', quiet=False)
df = pd.read_csv('dataset.csv')
print("Shape:", df.shape)

Downloading...
From: https://drive.google.com/uc?id=1x-phOl0d1QHy4ea8O_hHdz_wBGH35dRz&export=download
To: /content/dataset.csv
100%|██████████| 920k/920k [00:00<00:00, 100MB/s]

Shape: (10000, 12)

## Question 1.1: Missing Values Detection

**Task:** Identify columns with any missing values.

In [ ]:
missing_cols = df.columns[df.isna().any()].tolist()
print("Columns with missing values:", missing_cols)

Columns with missing values: ['Locality', 'Estimated Value', 'carpet_area']

## Question 1.2: Highest Missing Count

**Task:** Find the column with the highest number of missing values.

In [ ]:
most_missing_col = df.isna().sum().idxmax()
print("Column with most missing values:", most_missing_col)

Column with most missing values: Locality

## Question 1.3: Data Filtering

**Task:** Drop rows with more than 2 missing values and report the remaining sample count.

In [ ]:
q1_3_df = df[df.isna().sum(axis=1) <= 2]
print("Remaining samples:", q1_3_df.shape[0])

Remaining samples: 9978

## Final Results Summary Table

**Task:** Consolidate all computed answers into a clear summary DataFrame.

In [ ]:
summary_data = {
    "Question": ["Q1 (Unknown Count)", "Q6 (Recent Years)", "Q7 (Rooms/Baths)", "Q9 (Greenwich)", "Q10 (August Sales)", "Q11 (Top Locality)"],
    "Answer": [unknown_count, q6, q7, q9, august_rows, avg_price]
}
results_table = pd.DataFrame(summary_data)
display(results_table)

             Question     Answer
0  Q1 (Unknown Count)       1823
1   Q6 (Recent Years)       4749
2    Q7 (Rooms/Baths)       2730
3      Q9 (Greenwich)         42
4  Q10 (August Sales)       1050
5  Q11 (Top Locality)  Greenwich

In [ ]:
df.replace('?', pd.NA, inplace=True)

df_raw = pd.read_csv('dataset.csv')
unknown_count = (df_raw == '?').sum().sum()
print("Q1 unknown count:", unknown_count)

Q1 unknown count: 1823

In [ ]:
print("Q3 value:", df.iloc[692, 0])

print("Q4 value:", df.iloc[546, 7])

print("Q5 unique localities:", sorted(df['Locality'].dropna().astype(str).unique()))

Q3 value: 2009-11-16
Q4 value: 3
Q5 unique localities: ['Bridgeport', 'Fairfield', 'Greenwich', 'Norwalk', 'Stamford', 'Waterbury', 'West Hartford']

In [ ]:
missing_cols = df.columns[df.isna().any()].tolist()
print("Q6 columns with missing values:", missing_cols)

most_missing_col = df.isna().sum().idxmax()
print("Q7 most missing column:", most_missing_col)

q8_df = df[df.isna().sum(axis=1) <= 2]
print("Q8 remaining samples:", q8_df.shape[0])

q9_df = df.dropna()
print("Q9 remaining samples:", q9_df.shape[0])

Q6 columns with missing values: ['Locality', 'Estimated Value', 'Property', 'carpet_area']
Q7 most missing column: Property
Q8 remaining samples: 9917
Q9 remaining samples: 5449

ASSIGNMENT 1.2

In [ ]:
q1_df = df.iloc[::2]
print(q1_df.iloc[0, 3])

print(q1_df.iloc[332, 3])

q3_df = df.iloc[1::2]
print(q3_df.iloc[332, 3])

q4_df = df.iloc[:, 1::2]
print(q4_df.iloc[100, 5])

q5_df = df.iloc[::2, ::2]
print(q5_df.iloc[255, 3])

111440.0
256200.0
352940.0
West
Detached House

In [ ]:
recent_years = sorted(df['Year'].unique())[-6:]
q6 = df[df['Year'].isin(recent_years)].shape[0]
print(q6)

q7 = df[(df['num_rooms'] == 3) & (df['num_bathrooms'] == 3)].shape[0]
print(q7)

q8 = df[(df['num_rooms'] == 3) | (df['num_bathrooms'] == 3)].shape[0]
print(q8)

q9 = df[
    (df['Year'] == 2022) &
    (df['Locality'] == 'Greenwich') &
    (df['num_rooms'] == 3) &
    (df['Face'].isin(['North', 'East']))
].shape[0]
print(q9)

august_rows = df[pd.to_datetime(df['Date']).dt.month == 8].shape[0]
print(august_rows)

avg_price = df.groupby('Locality')['Sale Price'].mean().idxmax()
print(avg_price)

4749
2730
8591
42
1050
Greenwich